pops:
  BFgam:
    ['BFgam']
  UGgam:
    ['UGgam']
  WAgam:
    ['BFgam', 'GNgam', 'CMgam', 'GAgam', 'GHgam']
  WAcol:
    ['BFcol', 'GNcol', 'CIcol', 'GHcol']
zarr:
  2L:
    'data/ag1000g.phase2.ar1.pass/2L/'
  2R:
    'data/ag1000g.phase2.ar1.pass/2R/'
  3L:
    'data/ag1000g.phase2.ar1.pass/3L/'
  3R:
    'data/ag1000g.phase2.ar1.pass/3R/'
  X:
    'data/ag1000g.phase2.ar1.pass/X/'
haps:
  2L:
    'data/haplotypes/ag1000g.phase2.ar1.haplotypes.2L.gz'
  2R:
    'data/haplotypes/ag1000g.phase2.ar1.haplotypes.2R.gz'
  3L:
    'data/haplotypes/ag1000g.phase2.ar1.haplotypes.3L.gz'
  3R:
    'data/haplotypes/ag1000g.phase2.ar1.haplotypes.3R.gz'
  X:
    'data/haplotypes/ag1000g.phase2.ar1.haplotypes.X.gz'
samples:
  2L:
    'data/samples/ag1000g.phase2.ar1.samples.2L.gz'
  2R:
    'data/samples/ag1000g.phase2.ar1.samples.2R.gz'
  3L:
    'data/samples/ag1000g.phase2.ar1.samples.3L.gz'
  3R:
    'data/samples/ag1000g.phase2.ar1.samples.3R.gz'
  X:
    'data/samples/ag1000g.phase2.ar1.samples.X.gz'
maps:
  2L:
    'data/recombination_maps/Ag_2L.map'
  2R:
    'data/recombination_maps/Ag_2R.map'
  3L:
   'data/recombination_maps/Ag_3L.map'
  3R:
   'data/recombination_maps/Ag_3R.map'
  X:
   'data/recombination_maps/Ag_X.map'
sample_meta:
  'data/samples.meta.txt'
