pops:
  BFgam:
    ['BFgam']
  WAgam:
    ['BFgam', 'GNgam', 'CMgam', 'GAgam', 'GHgam']
  WAcol:
    ['BFcol', 'GNcol', 'CIcol', 'GHcol']
zarr:
  2L:
    '../data/ag1000g.phase2.ar1.pass/2L/'
  2R:
    '../data/ag1000g.phase2.ar1.pass/2R/'
  3L:
    '../data/ag1000g.phase2.ar1.pass/3L/'
  3R:
    '../data/ag1000g.phase2.ar1.pass/3R/'
  X:
    '../data/ag1000g.phase2.ar1.pass/X/'
haps:
  2L:
    'data/shapeit/ag1000g.phase2.ar1.haplotypes.2L.gz'
  2R:
    'data/shapeit/ag1000g.phase2.ar1.haplotypes.2R.gz'
  3L:
    'data/shapeit/ag1000g.phase2.ar1.haplotypes.3L.gz'
  3R:
    'data/shapeit/ag1000g.phase2.ar1.haplotypes.3R.gz'
  X:
    'data/shapeit/ag1000g.phase2.ar1.haplotypes.X.gz'
maps:
  2L:
    '../data/reference/recombination_maps/Ag_2L.map'
  2R:
    '../data/reference/recombination_maps/Ag_2R.map'
  3L:
   '../data/reference/recombination_maps/Ag_3L.map'
  3R:
   '../data/reference/recombination_maps/Ag_3R.map'
  X:
   '../data/reference/recombination_maps/Ag_X.map'
samples:
  '../data/samples.meta.txt'